Mesh Filter, Unit Tests, Refactoring, Pre-/Postprocessing Scripts
SeisSol/SAMPLER pull request #5
Opened 2021-08-11 11:05 UTC by mtronicsDev

2D faces are now automatically separated into seafloor and sea surface based on their altitude and orientation (not only based on height anymore).
Most of the procedures in the code now have unit tests. Call via `julia test/<test_name>.jl`.
To support unit tests, the code has been split up into smaller functions. Other refactorings have been done as well.
Pre- and postprocessing scripts that are part of some earthquake-tsunami piplines have been added.
Output variable mappings have been made more robust internally.

2021-08-23 14:24 UTC, krenzland requested changes

2021-08-30 09:11 UTC, mtronicsDev commented on src/io/netcdf.jl
> +
Yes, the headers were part of the standard template; I agree that they are a pain to deal with

2021-08-30 10:21 UTC, mtronicsDev reviewed
Feedback incorporated.

2021-08-30 10:24 UTC, krenzland approved these changes

2021-08-30 10:24 UTC, merged